### ISSUE TITLE
可否将插件上架至新版Edge浏览器的扩展商店？

### ISSUE THREAD

**Issue by Marsopera** [LouisYLWang/Sync-Sofa#10]
https://blogs.windows.com/msedgedev/2019/12/16/get-started-extensions-addons-microsoft-edge-chromium/

虽然Edge浏览器可以在Chrome的扩展商店里直接安装插件，但在国内需要全局翻墙。
Edge自己的扩展插件没有被墙，国内用户用起来会更方便一些。

插件很棒！

**Comment by LouisYLWang** [comment]
https://microsoftedge.microsoft.com/addons/detail/kpfbclpafmmjalikjjlcoddffpfgghgp
已上架Edge商店，由于微软商店审核时间较长，请注意核对两用户版本号是否一致

**Comment by xdlumia** [comment]
> https://microsoftedge.microsoft.com/addons/detail/kpfbclpafmmjalikjjlcoddffpfgghgp 已上架Edge商店，由于微软商店审核时间较长，请注意核对两用户版本号是否一致

您的edge商店审核一般多久呢？我之前都是两天 甚至几个小时就通过了，这次一周了还没有反应
