### ISSUE TITLE
推荐一个看电影的网站

### ISSUE THREAD

**Issue by ppshuh7** [LouisYLWang/Sync-Sofa#12]
我看了现在支持的duonao和danzanzan电影的画质都不是挺好的，这个网站电影画质就很不错http://www.dililitv.com/  
很棒的插件，大佬加油↖(^ω^)↗

**Comment by onns** [comment]
感谢推荐，最近新增了本地VLC的支持，你可以把你喜欢的电影下载到本地再播放！没有带宽和清晰度的限制，详情请移步至[VLC支持](https://onns.xyz/sync-sofa/#vlc-support)
