### ISSUE TITLE
大佬 快更新一个可以一起听歌的插件吧

### ISSUE THREAD

**Issue by MallonFeon** [LouisYLWang/Sync-Sofa#18]
最好是支持网易云的 感激不尽

**Comment by onns** [comment]
> 最好是支持网易云的 感激不尽

你听网易云会用网页听嘛？是不是很多歌，比如付费歌曲，必须要客户端才能听？

**Comment by onns** [comment]
> 最好是支持网易云的 感激不尽

嘿，我们已经最近支持了音乐同步，要不要抢先体验一下（可能会有一些莫名其妙的bug偶尔）
