### ISSUE TITLE
Couldn't customize port when using docker

### ISSUE THREAD

**Issue by BurgerTown** [LouisYLWang/Sync-Sofa#19]
PS. It didn't response after `./server`
Is that doesn't support customized port for client yet?

**Comment by LouisYLWang** [comment]
Sorry, it should support customized port, for both server and client side. The current server hosting script is outdated, I'll update later. Currently customized port for client need change relevant code manually, I'll explain in the new hosting script.

**Comment by BurgerTown** [comment]
I got Nginx running on my server so...
