### ISSUE TITLE
请求添加对本地视频文件的支持

### ISSUE THREAD

**Issue by petronny** [LouisYLWang/Sync-Sofa#20]
如题，可以是github pages host的一个静态网页，
然后只提供一个打开本地文件的播放器。

双方约定打开同一个文件即可

**Comment by onns** [comment]
hello～，请问你想打开的本地文件的格式是什么样的呢？

**Comment by petronny** [comment]
我可以自己压，就浏览器支持比较好的webm，mp4吧
h264是不奢望了。。。

**Comment by onns** [comment]
是的，H264因为版权的原因Chrome只能解析画面不能播放声音。
如果是mp4的话，插件已经支持了～你直接把mp4文件拖进浏览器即可
`file:///`前缀的视频文件，和其它视频网页一样的效果。

**Comment by onns** [comment]
建立连接
![用户一](https://onns.xyz/blog/image/20200626-1.png)
![用户二](https://onns.xyz/blog/image/20200626-2.png)

同步播放状态
![用户一](https://onns.xyz/blog/image/20200626-3.png)
![用户二](https://onns.xyz/blog/image/20200626-4.png)

**Comment by petronny** [comment]
必须要file开头么，存samba上的文件就不是file://开头了。。。

**Comment by onns** [comment]
另一个解决方案是建议你用网盘，[腾讯微云](https://www.weiyun.com/)了解一下，还不用考虑带宽问题，不过会员也是另一个问题23333。

不必要`file:///`开头，但是为了避免滥用权限所以插件设置的匹配规则里只有`file:///`的，如果你那边有什么新的协议可以告诉我，打个布丁上去分分钟，但是提交Chrome插件的更新版本就要延后了，你可以下载`dev-*`分支。

**Comment by onns** [comment]
你说的对，要点开[插件详情](chrome://extensions/?id=kgpnhgmpijhpkefpddoehhminpfiddmg)，允许`Allow access to file URLs`。

**Comment by petronny** [comment]
那我在想。。。VLC web control是不是可行？

**Comment by onns** [comment]
这个问题我想过，VLC的第三方插件列表里有同步播放的插件，你可以去试试。

这个可以后续支持吧，但如果叫一个用户为了做这些而下载VLC可能就有点要求过高了，所以这个功能的开发优先级没有那么高。

**Comment by petronny** [comment]
> 顺便一提，这个功能下也要额外下软件，第一次鼓弄的话，还真的蛮麻烦的。

但 VLC web control 就不需要额外软件了啊

**Comment by onns** [comment]
你刚刚的那个问题我开了新的issue，会在[新的issue](https://github.com/LouisYLWang/Sync-Sofa/issues/21)里回复你。

刚刚试了一下`VLC media player - Web Interface`，正如你所说，确实会方便许多，已经添加到 **TODO LIST** 里了。

**Comment by onns** [comment]
VLC支持已经push到`dev-ackversion`分支了，安装最新插件的方法[点这里](https://github.com/LouisYLWang/Sync-Sofa/tree/dev-ackversion#install-from-unpackaged-folder)，记得选择`development version`。

使用前请先配置好VLC，参照[Control VLC via a browser](https://wiki.videolan.org/Control_VLC_via_a_browser/)

使用方法参照[Usage](https://github.com/LouisYLWang/Sync-Sofa/tree/dev-ackversion#usage)

注意如果要使用beta版本，请先禁用Google商店下载的版本。
`If there are multiple versions of extensions in your browser, please enable one and disable others.`

VLC为最新的功能，暂时还没有写文档，请保证浏览器页面打开，在同步的过程中。
VLC的相关设置应为默认设置且不允许更改，即`127.0.0.1:8008`，否则插件无法识别。

如果有什么问题欢迎反馈～

**Comment by petronny** [comment]
好 我来试试

**Comment by petronny** [comment]
呃,`127.0.0.1:8008`?
默认不是8080端口么

**Comment by onns** [comment]
手误，已经修改

**Comment by onns** [comment]
刚刚有个可能导致服务器崩溃的修复小补丁打上去了，可能需要重新下载替换一下了，要刷新一下插件并且刷新一下控制页面（127.0.0.1:8080）

https://github.com/LouisYLWang/Sync-Sofa/archive/dev.zip

**Comment by petronny** [comment]
刚才试了一下，大概没问题，不过最后退出的时候有个不断弹窗“状态码为0”，大概原因是另一端断开了？

**Comment by onns** [comment]
尽量先关网页吧，这个问题不影响正常的使用，不过刚刚也打了补丁，应该是修复了。

感谢你提供的建议～期待你在后续使用中继续提供反馈和意见～

测试版的拓展会在近期的更新中实装，届时可以直接通过Chrome 商店下载，同时本issue会被关闭，如果后续有什么问题，可以创建新的issue。

如果觉得插件不错的话，欢迎推荐给有相同需求的人～十分感谢！
