### ISSUE TITLE
可以把api host做成一个插件选项么，这样self host了之后也方便输地址啊

### ISSUE THREAD

**Issue by onns** [LouisYLWang/Sync-Sofa#21]
可以把api host做成一个插件选项么，这样self host了之后也方便输地址啊

_Originally posted by @petronny in https://github.com/LouisYLWang/Sync-Sofa/issues/11#issuecomment-650259910_

**Comment by petronny** [comment]
主要是以下两个需求：

1. 能不能自定义端口号
1. 能不能把是否SSL也做一个选项？
主要是为了应对LAN的情形。

**Comment by onns** [comment]
已支持，[相关文档](https://github.com/LouisYLWang/Sync-Sofa/tree/dev#setting)

**Comment by onns** [comment]
话说你自己建服务器的原因也是因为，自带的服务器 服务不稳定吗？

**Comment by petronny** [comment]
对，默认的这个老断

**Comment by onns** [comment]
https://sync-cn.onns.xyz
新服务器，试试效果如何

**Comment by misaka-sakana** [comment]
你好 我自己self hold服务器的时候感觉连不上...
自己服务器用的是dev 模式 端口设置为3000 （因为服务器还hold其他网页 80端口已经被占用了） config如下
`{
    "addr": ":3000",
    "runmode": "dev"
}`

然后client端是 HTTP server_ip:3000 
输入房间号链接完全无反应...

请问设置有什么问题么？还是说输入port的格式不对？

Debug Mode下Console 输出如下 （只有这两行）

`2020-10-29 01:02:19 from the extension content.js:62   
2020-10-29 01:02:19 ask for status: ready content.js:62  
2020-10-29 01:02:23 from the extension content.js:62  
2020-10-29 01:02:23 ask for status: ready content.js:62  `

**Comment by onns** [comment]
为什么想要自己host呢？
如果你的网页协议是https，那socket的协议也必须是https，你可以开debug模式把控制台输出贴上来

**Comment by misaka-sakana** [comment]
> 为什么想要自己host呢？ 如果你的网页协议是https，那socket的协议也必须是https，你可以开debug模式把控制台输出贴上来

主要就是用服务器有时候经常断.. 想着自己有个专用的服务器会不会稳定点
我试试https，因为443端口已经bind了 对于https也可以用别的端口吧？
