### ISSUE TITLE
大佬能不能出一个docker的详细教程

### ISSUE THREAD

**Issue by huoranxuanyuan** [LouisYLWang/Sync-Sofa#25]
我照着您的代码安装docker一直报错，运行起来了插件也连不上，没有日志也不知道是哪块的问题。。

**Comment by onns** [comment]
方便的话，可以把相关的截图放上来嘛？

**Comment by huoranxuanyuan** [comment]
> 方便的话，可以把相关的截图放上来嘛？

![image](https://user-images.githubusercontent.com/67738326/86348341-2332cb80-bc92-11ea-91ee-f8e1e4d8938c.png)
命令行的都关了就不截了，我用portainer安装参数设置是这样的，端口映射因为里面没写具体的我映射的8000:8000

**Comment by onns** [comment]
客户端的话，请先确认版本号是不是1.0.6哈，如果可以顺便也告知一下安装的方式（Chrome商店或是自己安装）。
在1.0.6版本下打开插件[选项页](https://onns.xyz/sync-sofa/#options-page)
有debug模式，打开之后也可以顺带把上面的信息粘贴上来。

先看看是客户端那边的问题还是服务器端。

**Comment by huoranxuanyuan** [comment]
> 客户端的话，请先确认版本号是不是1.0.6哈，如果可以顺便也告知一下安装的方式（Chrome商店或是自己安装）。
> 在1.0.6版本下打开插件[选项页](https://onns.xyz/sync-sofa/#options-page)
> 有debug模式，打开之后也可以顺带把上面的信息粘贴上来。
> 
> 先看看是客户端那边的问题还是服务器端。

客户端是商店新装的，今天重装了几次，debug模式已经开了但是没看到有信息出现啊？

**Comment by onns** [comment]
emmm请问你有试过直接用默认的服务器能否成功吗？（其实我一直不太了解大家为什么都要自己架服务器端诶，其实我们这边是有架服务器的）

**Comment by huoranxuanyuan** [comment]
> emmm请问你有试过直接用默认的服务器能否成功吗？（其实我一直不太了解大家为什么都要自己架服务器端诶，其实我们这边是有架服务器的）

默认服务器看几分钟自动就断了。。我也不知道为什么

**Comment by onns** [comment]
噗！那大概率是服务器端的问题了，`RUNMODE`这个选项。。。是"prod" 或"dev"。。。你要不要再试试。。

**Comment by huoranxuanyuan** [comment]
> RUNMODE



> 噗！那大概率是服务器端的问题了，`RUNMODE`这个选项。。。是"prod" 或"dev"。。。你要不要再试试。。

看了眼宝塔那边，我映射的8000端口未使用，应该还是服务器配置问题

**Comment by onns** [comment]
我粗略的看了一眼你的截图，我的意思是，你看下你 `RUNMODE`这个参数。

**Comment by huoranxuanyuan** [comment]
> 我粗略的看了一眼你的截图，我的意思是，你看下你 `RUNMODE`这个参数。

那边我刚才两个都试过了，容器可以运行，但是没有网络连接，不知道是哪块设置的问题、

**Comment by onns** [comment]
docker不知道和系统版本有木有关系，冒昧地问下你的系统是。。
（有没有不用docker的这种说法，这个方法挺简单的）

**Comment by onns** [comment]
映射端口外面是随意但是里面的那个端口应该和你ADDR里的保持一致

**Comment by huoranxuanyuan** [comment]
好我再试试

**Comment by huoranxuanyuan** [comment]
好我再试试

**Comment by onns** [comment]
但我不知道https是不是强制443哈

**Comment by onns** [comment]
还有其中的所有参数其实你都不必填。。。只要
  ```json
  {
    "addr": ":80",
    "runmode": "dev"
  }
  ```
就行

**Comment by huoranxuanyuan** [comment]
> 还有其中的有些参数其实你都不必填。。。只要
> 
> ```json
> {
>   "addr": ":80",
>   "runmode": "dev"
> }
> ```
> 
> 就行
![image](https://user-images.githubusercontent.com/67738326/86368774-263cb480-bcb0-11ea-8a6c-09ff845cd6d4.png)

这回好像真运行起来了，插件也能生成码了，但是好像连不上，也没有连接的弹窗，每次打开都是首页得生成新码

**Comment by huoranxuanyuan** [comment]
> 还有其中的有些参数其实你都不必填。。。只要
> 
> ```json
> {
>   "addr": ":80",
>   "runmode": "dev"
> }
> ```
> 
> 就行

而且我https好像连不上，只能http

**Comment by onns** [comment]
80协议就是http，就用http就行

**Comment by onns** [comment]
你看下控制台的输出，shift ctrl i

**Comment by huoranxuanyuan** [comment]
> shift ctrl i

具体是看哪里?能截图示意一下吗

**Comment by huoranxuanyuan** [comment]
> 你看下控制台的输出，shift ctrl i

![image](https://user-images.githubusercontent.com/67738326/86371784-e8418f80-bcb3-11ea-979d-5810d96c2273.png)
是这个吗，有报警

**Comment by onns** [comment]
哦看来http不行
那你得加上
```json
"tlsdir": {
		"tlskey": "/etc/letsencrypt/live/your.host.url/privkey.pem",
		"tlscert": "/etc/letsencrypt/live/your.host.url/fullchain.pem"
	}
```
端口为443

**Comment by onns** [comment]
这样吧，你先甭折腾了，明天等我们完善一下文档，或者再考虑在国内架一台服务器。。。
我自己用居然一点问题都没发现，果然还是测试样本太少了吗。。。

**Comment by huoranxuanyuan** [comment]
> 这样吧，你先甭折腾了，明天等我们完善一下文档，或者再考虑在国内架一台服务器。。。
> 我自己用居然一点问题都没发现，果然还是测试样本太少了吗。。。

好，麻烦您了，主要也是我英语一窍不通看这些都费劲。

**Comment by onns** [comment]
https://sync-cn.onns.xyz
新服务器，试试效果如何

**Comment by huoranxuanyuan** [comment]
> https://sync-cn.onns.xyz
> 新服务器，试试效果如何

好，我等朋友试一下效果

**Comment by onns** [comment]
你之前在使用的时候，大概是多久断一次？

**Comment by huoranxuanyuan** [comment]
> 你之前在使用的时候，大概是多久断一次？

之前差不多五分钟左右？主要试的次数不太多，我本地开俩浏览器倒是没断过

**Comment by onns** [comment]
最新的代码更新了心跳逻辑，不过要过段时间才会更新到商店了，你可以通过源码安装，你的朋友用商店版本就行了，只要有一方用了，应该就可以避免类似情况的出现了～

记得用源码安装的时候要把商店安装的版本禁用，不然两个版本一起会冲突。

**Comment by huoranxuanyuan** [comment]
> 你之前在使用的时候，大概是多久断一次？

之前差不多五分钟左右？主要试的次数不太多，我本地开俩浏览器倒是没断过

> 最新的代码更新了心跳逻辑，不过要过段时间才会更新到商店了，你可以通过源码安装，你的朋友用商店版本就行了，只要有一方用了，应该就可以避免类似情况的出现了～
> 
> 记得用源码安装的时候要把商店安装的版本禁用，不然两个版本一起会冲突。

好的，我晚上试一下

**Comment by huoranxuanyuan** [comment]
> > 你之前在使用的时候，大概是多久断一次？
> 
> 之前差不多五分钟左右？主要试的次数不太多，我本地开俩浏览器倒是没断过
> 
> > 最新的代码更新了心跳逻辑，不过要过段时间才会更新到商店了，你可以通过源码安装，你的朋友用商店版本就行了，只要有一方用了，应该就可以避免类似情况的出现了～
> > 记得用源码安装的时候要把商店安装的版本禁用，不然两个版本一起会冲突。
> 
> 好的，我晚上试一下



> 最新的代码更新了心跳逻辑，不过要过段时间才会更新到商店了，你可以通过源码安装，你的朋友用商店版本就行了，只要有一方用了，应该就可以避免类似情况的出现了～
> 
> 记得用源码安装的时候要把商店安装的版本禁用，不然两个版本一起会冲突。

你们这个服务器对带宽有要求吗，我手里还有一个一年到期的腾讯云可以贡献出来做服务器，就是只有1m的上传

**Comment by onns** [comment]
可以呀～但会占用443端口，你在上面搭的网站可能就不行了。

**Comment by huoranxuanyuan** [comment]
> 可以呀～但会占用443端口，你在上面搭的网站可能就不行了。

QQ详细说？我网站现在没用https

**Comment by onns** [comment]
369449142
