### ISSUE TITLE
Bilibili电影似乎不能识别

### ISSUE THREAD

**Issue by hainingpan** [LouisYLWang/Sync-Sofa#26]
比如这个: https://www.bilibili.com/bangumi/play/ss28980?t=7

点击图标弹出的就是下拉菜单而不是request code的那个页面
![image](https://user-images.githubusercontent.com/22186947/86514036-e45d5c80-bddc-11ea-97ee-f0b840c42bb3.png)

**Comment by onns** [comment]
感谢反馈，确实如此，因为没有匹配到“bangumi”这个子目录，已经在dev的版本更新了，不过暂时只能通过[源码安装](https://onns.xyz/sync-sofa/#install-from-unpackaged-folder)来更新，下次更新会修复的。

**Comment by onns** [comment]
我推荐你和你的朋友通过迅雷下载这个电影然后通过vlc同步播放，这样可以免除充会员的烦恼，因为b站暂时不可用，十分抱歉😔

**Comment by hainingpan** [comment]
> 感谢反馈，确实如此，因为没有匹配到“bangumi”这个子目录，已经在dev的版本更新了，不过暂时只能通过[源码安装](https://onns.xyz/sync-sofa/#install-from-unpackaged-folder)来更新，下次更新会修复的。

谢谢, 用了dev的版本确实可以匹配了
