### ISSUE TITLE
Youku电影连接成功但是无法同步

### ISSUE THREAD

**Issue by hainingpan** [LouisYLWang/Sync-Sofa#27]
比如这个:
https://v.youku.com/v_show/id_XNDAxNzI5MDE0MA==.html?tpa=dW5pb25faWQ9MTAzNzUzXzEwMDAwMV8wMV8wMQ&refer=sousuotoufang_market.qrwang_00002944_000000_QJFFvi_19031900

连接成功但是并不能同步播放和暂停, Error如下:
![image](https://user-images.githubusercontent.com/22186947/86514787-51272580-bde2-11ea-86cc-c5e798973ae2.png)

**Comment by onns** [comment]
是这样的，优酷和芒果的播放控件是页面渲染之后添加的，所以请务必先等到整个页面渲染完成，且视频可以播放了之后再和你的朋友连接

**Comment by hainingpan** [comment]
> 是这样的，优酷和芒果的播放控件是页面渲染之后添加的，所以请务必先等到整个页面渲染完成，且视频可以播放了之后再和你的朋友连接

谢谢, 但我又试了一下, 确实是双方都已经可以播放了, 但是依然不能同步, 然后错误信息和之前的是一样的.

**Comment by onns** [comment]
你可以打开debug模式，像我这个ctrl shift i 打开控制台然后到console标签，我觉得不应还不行啊

![Screen Shot 2020-07-05 at 9 15 49 AM](https://user-images.githubusercontent.com/16622934/86523514-4763f780-bea0-11ea-812a-85715eb8ecc8.png)
![Screen Shot 2020-07-05 at 9 15 49 AM (2)](https://user-images.githubusercontent.com/16622934/86523516-4d59d880-bea0-11ea-8f9a-b7f09fb484a1.png)

**Comment by onns** [comment]
已修复。

**Comment by hainingpan** [comment]
谢谢, 我试了一下, 似乎你改变了现在版本的行为(当整个页面没有渲染完成的时候, 不可以request new code)

然后我就发现一直都是灰色的
![image](https://user-images.githubusercontent.com/22186947/86544278-88d1c280-bef3-11ea-9083-ab6798d6cc46.png)

**Comment by onns** [comment]
你说的对，我确实强制了渲染完成才能申请code。

你是不是本人不在中国大陆？感觉你这个网页有好多本来该加载的资源却没有加载（可能是因为区域的原因）

我们正常打开的时候只有黄色的警告，没有红色的报错，所以我觉得你要不清除一下cache？（不是cookie）

方法是，ctrl shift i，选择到network的标签，然后刷新网页，在任意链接右键，clear cache

**Comment by hainingpan** [comment]
确实如此, clear cache就好了

**Comment by onns** [comment]
所有更新都已发布在1.0.7版且已上线chrome商店，可以直接去下载最新版（记得禁用本地安装的版本）
