### ISSUE TITLE
连接经常断开，需要重新创建房间，希望优化下

### ISSUE THREAD

**Issue by hms58** [LouisYLWang/Sync-Sofa#28]

**Comment by onns** [comment]
有配置服务器吗？[服务器列表](https://onns.xyz/sync-sofa/#%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%88%97%E8%A1%A8)

**Comment by hms58** [comment]
> 有配置服务器吗？[服务器列表](https://onns.xyz/sync-sofa/#%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%88%97%E8%A1%A8)

没有，是服务器问题？

**Comment by onns** [comment]
点进去，看一下

**Comment by hms58** [comment]
> 点进去，看一下

好的，谢谢
