### ISSUE TITLE
问您两个问题

### ISSUE THREAD

**Issue by Baccanoooo** [LouisYLWang/Sync-Sofa#29]
服务器已换
1.点了申请新房间码后，过会儿插件弹窗自动关闭，再点插件图标呼出插件时，刚刚创建的房间不见了
2.加入的时候输入别人的房间码，点start，自动变了个码，也没什么反应
不知道什么情况

**Comment by onns** [comment]
逻辑是这样的：
1. 你点击申请码，会收到一个码，并自动复制到剪切板，三秒后插件自动隐藏，此时，在同一个窗口点击插件，是还会看到相应的房间码的。
![Screen Shot 2020-07-11 at 3 46 28 PM](https://user-images.githubusercontent.com/16622934/87219441-b56f5980-c38d-11ea-9e66-551ef2dbef0b.png)

2. start之后确实会变（变了才代表连接成功），之后你可以注意一下页面会有连接成功提示的弹窗。

**Comment by Baccanoooo** [comment]
2我知道啦，谢谢您哦；1的话，我一开始也能成功，但是后来申请过了隐藏了之后，在同一个页面再打开插件，刚刚的码不见了，又成了刚打开时的样子（申请和开始两个按钮）

**Comment by Baccanoooo** [comment]
一开始是有成功过两次的，但是好像不太稳定，然后换了杭州的服务器，就这样了

**Comment by onns** [comment]
请打开debug模式，ctrl shift i  在选项里选console，把相关的输出截图或粘贴到这里来

**Comment by Baccanoooo** [comment]
![image](https://user-images.githubusercontent.com/63040635/87219636-6d513680-c38f-11ea-9a30-90c01b61c4f1.png)

**Comment by onns** [comment]
有刷新页面吗？

**Comment by Baccanoooo** [comment]
刷新了，重启浏览器也试了下，就差重启电脑了

**Comment by onns** [comment]
很奇怪。。。我这边是正常连接的，而且这个socket弹出来未知错误，是之前从来没人遇到的。。。

**Comment by Baccanoooo** [comment]
我再换个服务器试下吧

**Comment by Baccanoooo** [comment]
诶，用北京的服务器没问题，杭州的就是未知错误

**Comment by onns** [comment]
玄学，所有服务器运行着相同的代码，不过能用就行，两端要保证服务器一致。

**Comment by onns** [comment]
可以看下你Chrome的版本号吗？

**Comment by Baccanoooo** [comment]
83.0.4103.116

**Comment by Baccanoooo** [comment]
我们试啦，换北京的可以正常使用，谢谢啦

**Comment by onns** [comment]
好的，如果有机会不要吝啬帮我宣传一下吧！
如果没别的问题就把此issue close掉吧。

**Comment by Baccanoooo** [comment]
嗯嗯，一定哈
