### ISSUE TITLE
[新功能] 永久连接 && 连接状态实时显示 && 自动重连

### ISSUE THREAD

**Issue by iaeolous** [LouisYLWang/Sync-Sofa#30]
**1. 永久连接**
每次都要输码配对有点麻烦，而且每次码都变来变去。所以，可不可以连接一次就永久保持配对。或者，永久记住这个码也行，需要用时再手动start。

**2. 连接状态实时显示**
就像这个Video Speed Controller插件一样, 会在视频左上角显示一个透明小窗。可以用一个小红点表示未配对，小绿点表示配对成功。因为有时候以为其他原因配对断开后也没有提示，貌似主动关闭才有提示。
![image](https://user-images.githubusercontent.com/17198878/89123353-42c34b00-d501-11ea-8245-08bd33f2d426.png)

**3. 自动重连**
希望可以实现配对断开后自动重连的功能。

**Comment by onns** [comment]
感谢你的反馈！
第三个问题就目前而言，因为没办法判断是用户主动断开的，还是网络原因断开的。目前的服务应该还比较稳定吧？你会遇到很多次断开的情况嘛？有更新到最新版嘛？或者尝试换服务器
第二个问题我们已经纳入`todo list`了，近期发布新版！
第一个问题，我觉得你从用户的角度想，确实是永久的更方便些，但会有人抢占一些简单的ID，或者重复的ID连接（如果你和好友连上了，但是被一个人不小心或者故意挤掉了，我相信体验一定很差）。在找到合理的解决方法前，可能还是目前的随机配对码较为实用。

**Comment by iaeolous** [comment]
第一个问题是服务器问题, 用的默认美国的, 改了之后应该就ok了。
那么第一个问题是否可以通过注册账号的方式来实现呢，每个用户绑定一个随机分配的ID。
