### ISSUE TITLE
Website suggestion

### ISSUE THREAD

**Issue by Doom-Prophet** [LouisYLWang/Sync-Sofa#33]
Actually I am a native user, so sometimes might need to watch videos in 百度云 or dilidili, 樱花动漫，风车动漫. I really love your project!!!! Thanks a lot and keep it on!!!

**Comment by onns** [comment]
百度云无法支持，建议用微云
你可以自己试试修改代码来添加支持，[这是个例子](https://github.com/LouisYLWang/Sync-Sofa/commit/041a5e356128c8b986115cac22fcfdb8f5c04131)。
