### ISSUE TITLE
VLC播放本地视频时使用8080以外的端口无法获取连接码

### ISSUE THREAD

**Issue by Ink-Bamboo** [LouisYLWang/Sync-Sofa#35]
_**我搞明白了 只有使用8080端口才能被识别**_

插件界面和申请连接码

使用VLC播放本地视频时无法获取连接码 （web控制页正常）

 - 插件版本号： 1.0.9
 - 连接的服务器域名（如为自建服务器，请注明）：三个服务器都不行
 - 操作系统：win10 2004 专业版
 - 浏览器型号：chrome edge
 - 浏览器版本号： 85.0.4183.83（正式版本） （64 位） 版本 86.0.622.3 (官方内部版本) dev (64 位)
 - 下载渠道：谷歌应用商店
![批注 2020-09-05 163613](https://user-images.githubusercontent.com/62972746/92301378-f8b50580-ef95-11ea-9442-b9fa78cf2ded.png)
![批注 2020-09-05 163715](https://user-images.githubusercontent.com/62972746/92301392-1da97880-ef96-11ea-87a0-0f4c9b23aa21.png)

不能获取连接码 开始按钮无效

**Comment by onns** [comment]
必须是8080端口

**Comment by onns** [comment]
请问一下你是8080端口被占用了吗？因为VLC和正常的视频页面都是完全不同的逻辑，所以程序一开始就要判断是不是VLC的控制页面，但是如果用VLC的页面里的元素来判断是不是VLC控制页面，可能会出现误判，所以最简单也最优雅的就是判断端口。

**Comment by Ink-Bamboo** [comment]
> 请问一下你是8080端口被占用了吗？ 因为VLC和正常的视频页面都是完全不同的逻辑，所以程序一开始就要判断是不是VLC的控制页面，但是如果用VLC的页面里的元素来判断是不是VLC控制页面，可能会出现误判，所以最简单也最优雅的就是判断端口。

是的 我刚发现是自己的8080端口被别的服务占用了 导致无法打开VLC的web控制页面 最后更换为8888端口而且需要外网才能正常打开web控制页面 此时就不能获取连接码

这个我整整研究了一天半才终于能用了 vlc和该插件的说明文档都翻了好几遍

总结一下
**_1. 在“通过Web控制界面操控VLC播放”的说明中建议添加注意事项 提示8080端口占用的问题

2.要想正常打开VLC的web控制页面 首次加载时得使用外网 不然会出现网页排版错误的现象（我在这里卡了好久 找不出原因）_**

**Comment by onns** [comment]
1. 8080端口占用不是我能检测到的，所以这个是真的没办法了，我在文档里加一些描述吧

2. VLC这个页面的jquery库引用的是google的cdn，所以在国内是没办法直接引用的，这点我也加上吧。

**Comment by Ink-Bamboo** [comment]
> 1. 8080端口占用不是我能检测到的，所以这个是真的没办法了，我在文档里加一些描述吧
> 2. VLC这个页面的jquery库引用的是google的cdn，所以在国内是没办法直接引用的，这点我也加上吧。

嗯嗯 好的 谢谢了
