### ISSUE TITLE
[enhancement]能否支持局域网内视频同步

### ISSUE THREAD

**Issue by dyxang** [LouisYLWang/Sync-Sofa#39]
如题，主要是出现以下需求

- 和伙伴都想看同一个电影，奈何无论哪方的设备两个人都太小了点，所以想用这个插件，奈何需要服务器且延迟的话要是两个人不在同一个地方也没啥，但是我是两个人在同一个房间，会有重音。
ps：要是这个需求太奇怪我还是 close this issue 吧

**Comment by onns** [comment]
其实这个功能是可以实现的，我自己就在自己电脑上完成过，不过就不能用商店版本了，需要用源代码版本。

**Comment by dyxang** [comment]
> 其实这个功能是可以实现的，我自己就在自己电脑上完成过，不过就不能用商店版本了，需要用源代码版本。

请问如何操作呢？

**Comment by onns** [comment]
你如果觉得麻烦点可以接受，我可以告诉你方法。

**Comment by dyxang** [comment]
> 你如果觉得麻烦点可以接受，我可以告诉你方法。

需要额外的服务器吗？如果是那就算了

**Comment by onns** [comment]
你先把代码按照教程里的导入进chrome，然后拿出任何一个文本编辑器打开`content.js`这个文件，第888行这里有个数字3，你改成一个很小的数字，比如0.01这种，在拖动后可能有无尽的鬼畜，但是你只要拖动后暂停，你可以保证两边的误差很小的。
https://github.com/LouisYLWang/Sync-Sofa/blob/2cc0cbcf95bf072546d6a735c674fc9f6a6351f8/client/chrome_extension/content.js#L888

使用的时候需要把商店版本的禁用掉。

**Comment by dyxang** [comment]
> 你先把代码按照教程里的导入进chrome，然后拿出任何一个文本编辑器打开`content.js`这个文件，第888行这里有个数字3，你改成一个很小的数字，比如0.01这种，在拖动后可能有无尽的鬼畜，但是你只要拖动后暂停，你可以保证两边的误差很小的。
> https://github.com/LouisYLWang/Sync-Sofa/blob/2cc0cbcf95bf072546d6a735c674fc9f6a6351f8/client/chrome_extension/content.js#L888
> 
> 使用的时候需要把商店版本的禁用掉。

嗯修改好了，不过是在我这边的第760行（使用vscode），到最后一步发现不管用，因为我们是在**局域网网页分享视频（即类似浏览器直接打开mp4的效果）**来看电影的，所以用不了，打扰了。

**Comment by onns** [comment]
https://share.weiyun.com/wjZO0iue
其实确实只有局域网才能做到这种效果，不然除非把服务器架在本地，不然不能更快了 = =！
你可以只开一台电脑的声音。

**Comment by dyxang** [comment]
> https://share.weiyun.com/wjZO0iue
> 其实确实只有局域网才能做到这种效果，不然除非把服务器架在本地，不然不能更快了 = =！
> 你可以只开一台电脑的声音。

原来如此，可是为啥我的局域网文件播放时扩展图标是灰色的点不开

**Comment by onns** [comment]
因为局域网我们没匹配。。。
修改一下[https://github.com/LouisYLWang/Sync-Sofa/blob/master/client/chrome_extension/background.js](https://github.com/LouisYLWang/Sync-Sofa/blob/master/client/chrome_extension/background.js)和https://github.com/LouisYLWang/Sync-Sofa/blob/master/client/chrome_extension/manifest.json
我也不知道你们家局域网是啥网址，不过你可以在这里暴力加个`http://*`

**Comment by dyxang** [comment]
> 因为局域网我们没匹配。。。
> 修改一下https://github.com/LouisYLWang/Sync-Sofa/blob/master/client/chrome_extension/background.js和https://github.com/LouisYLWang/Sync-Sofa/blob/master/client/chrome_extension/manifest.json
> 我也不知道你们家局域网是啥网址，不过你可以在这里暴力加个`http://*`

好的谢谢啦
