### ISSUE TITLE
GFW support

### ISSUE THREAD

**Issue by whtitefall** [LouisYLWang/Sync-Sofa#4]
请问一下支持墙内墙外视频同步吗

因为试了试bilibli，但是貌似墙内墙外的连接不能用，不确定是否因为操作原因还是本身不支持

谢谢

**Comment by LouisYLWang** [comment]
理论上应该是不受墙的限制，我再写一个再详细一些的教程，也可能是因为bug

**Comment by LouisYLWang** [comment]
下个版本添加支持

**Comment by whtitefall** [comment]
> 下个版本添加支持

好的 谢谢！

**Comment by onns** [comment]
已经支持了哦～可以试用一下最新版！
