### ISSUE TITLE
[BUG]一方被插件暂停 且无法恢复播放

### ISSUE THREAD

**Issue by LiYeLin** [LouisYLWang/Sync-Sofa#41]
**哪个环节操作发生问题**
播放同步

背景网站：腾讯视频
两个人在同步播放的时候 会出现一方忽然暂停的情况，然后另一方继续在播放 ，暂停的那方点击播放按钮 播放0.1s就会又被插件暂停住  ，无法稳定复现，但是出现1次之后 就会经常出现了 目前和女朋友看了三部电影了 分别遇到这个情况1次 3次  最后一部电影无数次 以至于无法看 期间试过双方重启浏览器 重新进入新房间 但是还会出现的

**使用环境**
windows chrome 插件版本最新

**其他**

**截图（可选）**
截图无法展示

**Comment by LouisYLWang** [comment]
请问是哪个服务器？使用位置是哪里？

**Comment by onns** [comment]
你电脑里是不是之前改过代码，两个版本共存

**Comment by LiYeLin** [comment]
> 请问是该服务器？使用位置是哪里？

![image](https://user-images.githubusercontent.com/29306500/106117969-8c2de380-618e-11eb-89ca-874774a6ee5b.png)
期间尝试过更换服务器 更换前的忘了 更换后双方都是这个

**Comment by LiYeLin** [comment]
> 请问是该服务器？使用位置是哪里？

女朋友说沙发右下角的图标按钮经常会变红 会是网络原因引起的吗

**Comment by LiYeLin** [comment]
> 你电脑里是不是之前改过代码，两个版本共存

没有哦 没自己动过

**Comment by onns** [comment]
> > 请问是该服务器？使用位置是哪里？
> 
> 女朋友说沙发右下角的图标按钮经常会变红 会是网络原因引起的吗

是的，变红代表连接断了，建议换国内的服务器

**Comment by LiYeLin** [comment]
请问有可用的服务器列表吗 还是需要自己搭建 我的服务器现在都是在亚马逊上

**Comment by LiYeLin** [comment]
> > > 请问是该服务器？使用位置是哪里？
> > 
> > 
> > 女朋友说沙发右下角的图标按钮经常会变红 会是网络原因引起的吗
> 
> 是的，变红代表连接断了，建议换国内的服务器

↑

**Comment by onns** [comment]
> 请问有可用的服务器列表吗 还是需要自己搭建 我的服务器现在都是在亚马逊上

= =写了文档都没人看的吗= =
[https://onns.xyz/sync-sofa/#server-list](https://onns.xyz/sync-sofa/#server-list)

**Comment by LiYeLin** [comment]
> > 请问有可用的服务器列表吗 还是需要自己搭建 我的服务器现在都是在亚马逊上
> 
> = =写了文档都没人看的吗= =
> https://onns.xyz/sync-sofa/#server-list

2333不好意思当时着急用 就没仔细看 我换上国内节点试试8

**Comment by onns** [comment]
hello 打扰一下，最近可能频繁地会更新代码，想听听其他人的使用意见，因为没有女朋友（心酸），你介不介意来帮我们体验一些新功能，比如视频通话等！

**Comment by LiYeLin** [comment]
好的，我们最近使用的还挺频繁的，如果有关于新功能的看法和反馈都会反映给你的！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Onns <notifications@github.com&gt;
发送时间: 2021年1月31日 15:44
收件人: LouisYLWang/Sync-Sofa <Sync-Sofa@noreply.github.com&gt;
抄送: 李业林 <im.liyelin@gmail.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[LouisYLWang/Sync-Sofa] [BUG]一方被插件暂停 且无法恢复播放 (#41)

**Comment by onns** [comment]
如果可以也可以加我微信哈哈哈，13219960804
话说我们最近上线了视频通话功能，可以找你试试哈哈哈哈
