### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Lskeats** [LouisYLWang/Sync-Sofa#47]
**感谢你的反馈，在反馈前，请先检查[指南文档常见问题部分](https://github.com/LouisYLWang/Sync-Sofa/blob/dev/readme.md)，若仍无法解决您的问题，请按照格式提供下列信息**

**哪个环节操作发生问题**
（插件安装/插件界面/申请连接码/连接用户/播放同步/设置选项/其他：请注明）
播放同步

**请在此处简洁地描述你遇到的问题**
和异地另一台电脑连接成功之后，我和他的电脑进度不一致，固定相差2分钟左右，之前没有该bug，两台电脑都更新最新版之后就一直有时间差，重装sofa也还是这样，两边都是chrome最新版。

**使用环境**
 - 插件版本号： 1.0.10
 - 连接的服务器域名（如为自建服务器，请注明）：
 - 操作系统：win10
 - 浏览器型号：chrome
 - 浏览器版本号：88.0.4324.182（正式版本）
 - 下载渠道（插件商店，商店镜像站（请注明），github）：chrome插件中心

**其他**
如需要，请补充你的问题详情

**截图（可选）**
如方便，请附上问题截图

**Comment by onns** [comment]
什么视频平台？

**Comment by Lskeats** [comment]
b站

**Comment by Lskeats** [comment]
刚刚测了下爱奇艺也有这个问题，连接成功后播放，他那是0分开始，我这直接跳到2分43开始,暂停和播放都是同步的，就是进度不一样

**Comment by onns** [comment]
那先请你们两个分别自测一下各自的功能是否有问题，同一个电脑开两个标签页打开同一个视频然后互相同步：
![Screen Shot 2021-02-26 at 2 34 18 AM (2)](https://user-images.githubusercontent.com/16622934/109200432-91a53a80-77db-11eb-8371-9476a624cca3.png)
然后测试一下是否出现异常：
![Screen Shot 2021-02-26 at 2 34 37 AM (2)](https://user-images.githubusercontent.com/16622934/109200453-9833b200-77db-11eb-9326-5b58af05d1cd.png)
![Screen Shot 2021-02-26 at 2 35 00 AM (2)](https://user-images.githubusercontent.com/16622934/109200512-abdf1880-77db-11eb-95f4-93fca5a65bb9.png)
如果双方都没问题，请找一个时间联系我和你们测试一下，看看是什么问题，我们自己测试都没问题感觉。

邮箱联系：onns@onns.xyz
或微信：13219960804
