### ISSUE TITLE
[BUG] 有固定时间差异

### ISSUE THREAD

**Issue by Ciaoye** [LouisYLWang/Sync-Sofa#48]
**哪个环节操作发生问题** 播放同步

**请在此处简洁地描述你遇到的问题**
双方有固定的时间差，例如 B 比 A 快 40s。
例：A 在 0s，B 会同步到 40s。此时 B 切到 20s 时，A 不变。B 切换到 60s，A 到 20s。A 切换到 40s，B 切到 80s。
B 播放完毕，A 停在 [视频时长-20s]。此时 A 点播放，B 会从头开始。

第一次触发原因：sync 观看 zoom record 视频（应该不在支持网站上，但是可以 sync）。A 点击了非播放器下方的时间戳，而点击了右侧的字幕时间往前跳了40s。
重启 chrome，改变房间，改变观看网站（youtube或者b站）无效。双方重装插件修复。

第二次触发原因：未知。差了 5s。可能还是和 sync 观看 zoom record 有关。
双方都在自己的浏览器里开两个页面和自己同步，没有出现问题。

**使用环境  A**
 - 插件版本号：1.0.10
 - 连接的服务器域名（如为自建服务器，请注明）：
 - 操作系统：MacOS 10.15.5
 - 浏览器型号：chrome
 - 浏览器版本号：Version 88.0.4324.192 (Official Build) (x86_64)
 - 下载渠道（插件商店，商店镜像站（请注明），github）：chrome extension

**使用环境  B**
 - 插件版本号：1.0.10
 - 连接的服务器域名（如为自建服务器，请注明）：
 - 操作系统：Win10
 - 浏览器型号：chrome
 - 浏览器版本号：版本 88.0.4324.190（正式版本） （64 位）
 - 下载渠道（插件商店，商店镜像站（请注明），github）：chrome extension

**其他**
想知道如果发生这个问题怎么 reset…感觉不是大问题但是挺难受的。 

需要的话可以复现一下。

**Comment by onns** [comment]
请问你们什么时候有时间，可以和我做一个测试，大概20分钟，我大概知道问题出在哪里了

**Comment by onns** [comment]
问题出在你们两人的系统时间没有同步，请同步一下系统时间。

**Comment by naliece** [comment]
> 具体同步系统时间是什么意思？这个问题我感觉是突然触发而不是长期存在的
