### ISSUE TITLE
[BUG] 运行时发生错误

### ISSUE THREAD

**Issue by bbx429** [LouisYLWang/Sync-Sofa#49]
# ./server
found config file, read parameters from config file...
2021/03/12 10:39:27 server is listening at :8001...
然后chrome浏览器插件连接
2021/03/12 10:39:31 http: panic serving 61.142.234.85:11630: runtime error: invalid memory address or nil pointer dereference
goroutine 6 [running]:
net/http.(*conn).serve.func1(0xc00006d040)
        c:/go/src/net/http/server.go:1772 +0x139
panic(0x700a60, 0x9d6100)
        c:/go/src/runtime/panic.go:973 +0x3e3
github.com/LouisYLWang/Sync-Sofa/server/session.Store.BeginSessions(0xc000051050, 0x34630b8a000, 0x0, 0xc0000d6200, 0x0, 0x0, 0x0, 0x0)
        C:/Users/louis/workdir/Sync-Sofa dev/Sync-Sofa/server/session/session.go:84 +0x37f
github.com/LouisYLWang/Sync-Sofa/server/handlers.(*Context).SessionSpecificHandler(0xc00000c420, 0x7d5020, 0xc0000be0e0, 0xc0000d6200)
        C:/Users/louis/workdir/Sync-Sofa dev/Sync-Sofa/server/handlers/sessionHandler.go:40 +0xbe
net/http.HandlerFunc.ServeHTTP(0xc000010e90, 0x7d5020, 0xc0000be0e0, 0xc0000d6200)
        c:/go/src/net/http/server.go:2012 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000b6000, 0x7d5020, 0xc0000be0e0, 0xc0000d6000)
        C:/Users/louis/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
github.com/LouisYLWang/Sync-Sofa/server/handlers.(*CORS).ServeHTTP(0xc000010f40, 0x7d5020, 0xc0000be0e0, 0xc0000d6000)
        C:/Users/louis/workdir/Sync-Sofa dev/Sync-Sofa/server/handlers/cors.go:38 +0x3c7
net/http.serverHandler.ServeHTTP(0xc0000be000, 0x7d5020, 0xc0000be0e0, 0xc0000d6000)
        c:/go/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc00006d040, 0x7d5720, 0xc00006a380)
        c:/go/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:2933 +0x35c

其他：客户端连接时错误

**请在此处简洁地描述你遇到的问题**

**使用环境**
 - 插件版本号： Sync Sofa 版本 1.0.10
 - 连接的服务器域名（如为自建服务器，请注明）：sync.bibix.cn:8001
 - 操作系统：Linux VM-0-11-centos 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - 浏览器型号：Google Chrome
 - 浏览器版本号：89.0.4389.82
 - 下载渠道（插件商店，商店镜像站（请注明），github）：谷歌商店

**其他**

**截图（可选）**
![image](https://user-images.githubusercontent.com/25520342/110885302-93b1e200-8321-11eb-9693-f00318ab1ee1.png)

**Comment by onns** [comment]
请问`server`文件在哪里下载的？

**Comment by bbx429** [comment]
> 请问`server`文件在哪里下载的？
server下载路径
https://github.com/LouisYLWang/Sync-Sofa/releases/download/1.0.6/server


你好，我是根据 https://onns.xyz/sync-sofa/#%E7%9B%B4%E6%8E%A5%E9%83%A8%E7%BD%B2%EF%BC%88%E4%B8%8D%E4%BD%BF%E7%94%A8docker%E5%AE%B9%E5%99%A8%EF%BC%89

如果无需修改源代码并自行编译，你也可以直接下载二进制文件:
打开 Github release page
下载 server 文件（适用于linux服务器）
下载 config.json 文件，移动至server同一路径
开发模式（http）配置文件样例:
  "addr": ":8001",
  "runmode": "dev"

**Comment by onns** [comment]
[server.zip](https://github.com/LouisYLWang/Sync-Sofa/files/6128012/server.zip)
用这个

**Comment by bbx429** [comment]
> [server.zip](https://github.com/LouisYLWang/Sync-Sofa/files/6128012/server.zip)
> 用这个

好的，我试试
