### ISSUE TITLE
[个人问题] 生产模式的证书配置

### ISSUE THREAD

**Issue by bbx429** [LouisYLWang/Sync-Sofa#50]
**哪个环节操作发生问题**
./server

**请在此处简洁地描述你遇到的问题**
1、使用的腾讯云免费证书
2、下载IIS文件下的 sync.bibix.cn.pfx 转换 pem
openssl pkcs12 -in sync.bibix.cn.pfx -nokeys -out cert.pem
openssl pkcs12 -in sync.bibix.cn.pfx -nokeys -nocerts -out key.pem -nodes
3、配置文件
{
  "addr": ":443",
  "runmode": "prod",
  "tlsdir": {
    "tlskey": "/opt/sync-sofa/1/key.pem",
    "tlscert": "/opt/sync-sofa/1/cert.pem"
  }
}

运行
# ./server
found config file, read parameters from config file...
一直卡在读取配置文件

**使用环境**
 - 插件版本号： Sync Sofa 版本 1.0.10
 - 连接的服务器域名（如为自建服务器，请注明）：sync.bibix.cn:443
 - 操作系统：Linux VM-0-11-centos 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - 浏览器型号：Google Chrome
 - 浏览器版本号：89.0.4389.82
 - 下载渠道（插件商店，商店镜像站（请注明），github）：谷歌商店

**Comment by onns** [comment]
提示这句话就代表已经运行了。












Onns
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月12日(周五) 下午3:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: [LouisYLWang/Sync-Sofa] [个人问题] 生产模式的证书配置 (#50)




 
哪个环节操作发生问题
 ./server
 
请在此处简洁地描述你遇到的问题
 1、使用的腾讯云免费证书
 2、下载IIS文件下的 sync.bibix.cn.pfx 转换 pem
 openssl pkcs12 -in sync.bibix.cn.pfx -nokeys -out cert.pem
 openssl pkcs12 -in sync.bibix.cn.pfx -nokeys -nocerts -out key.pem -nodes
 3、配置文件
 {
 "addr": ":443",
 "runmode": "prod",
 "tlsdir": {
 "tlskey": "/opt/sync-sofa/1/key.pem",
 "tlscert": "/opt/sync-sofa/1/cert.pem"
 }
 }
 
运行
 
./server
 
found config file, read parameters from config file...
 一直卡在读取配置文件
 
使用环境
  
插件版本号： Sync Sofa 版本 1.0.10 

连接的服务器域名（如为自建服务器，请注明）：sync.bibix.cn:443 

操作系统：Linux VM-0-11-centos 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux 

浏览器型号：Google Chrome 

浏览器版本号：89.0.4389.82 

下载渠道（插件商店，商店镜像站（请注明），github）：谷歌商店
