### ISSUE TITLE
[BUG]进度条一下子拖动的的特别远会出现双方卡死的问题

### ISSUE THREAD

**Issue by goodnighteveryone** [LouisYLWang/Sync-Sofa#51]
**感谢你的反馈，在反馈前，请先检查[指南文档常见问题部分](https://github.com/LouisYLWang/Sync-Sofa/blob/dev/readme.md)，若仍无法解决您的问题，请按照格式提供下列信息**

**哪个环节操作发生问题**
（插件安装/插件界面/申请连接码/连接用户/播放同步/设置选项/其他：请注明）
播放同步

**请在此处简洁地描述你遇到的问题**
连接成功之后，如果把进度条拖动到很远的地方（比如5分钟），就会出现双方同时卡死的情况
**使用环境**
 - 插件版本号： 1.0.10
 - 连接的服务器域名（如为自建服务器，请注明）：api.huoranxuanyuan.cn
 - 操作系统：win10
 - 浏览器型号：chrome edge
 - 浏览器版本号：chrome 89.0.4389.90，edge89.0.774.50
 - 下载渠道（插件商店，商店镜像站（请注明），github）：chrome插件商店

**其他**
如需要，请补充你的问题详情

**截图（可选）**
如方便，请附上问题截图
![image](https://user-images.githubusercontent.com/49894559/111020857-aef51e00-8403-11eb-94c6-50ae41b9c137.png)

![1](https://user-images.githubusercontent.com/49894559/111020648-7a349700-8402-11eb-81c8-ee10286c7370.png)

**Comment by LouisYLWang** [comment]
请问server文件是哪里下载的？

**Comment by goodnighteveryone** [comment]
> 请问server文件是哪里下载的？

请问server文件是什么？扩展文件吗？

**Comment by LouisYLWang** [comment]
哦抱歉我以为你是自己host的服务器

**Comment by onns** [comment]
应该是加载缓存的问题吧？视频是需要时间缓存的，那时候会被暂停

**Comment by goodnighteveryone** [comment]
> 应该是加载缓存的问题吧？视频是需要时间缓存的，那时候会被暂停

应该不是吧，做过几次测试，即使在加载几分钟的情况下视频还是会卡在那。最好的情况是有一台电脑的视频能动了，不过因为另一台电脑卡死的缘故，播放几秒之后还会回到和另一台电脑相同的位置再次播放

**Comment by LouisYLWang** [comment]
> 
> 
> > 应该是加载缓存的问题吧？视频是需要时间缓存的，那时候会被暂停
> 
> 应该不是吧，做过几次测试，即使在加载几分钟的情况下视频还是会卡在那。最好的情况是有一台电脑的视频能动了，不过因为另一台电脑卡死的缘故，播放几秒之后还会回到和另一台电脑相同的位置再次播放

是不是edge卡死？chrome正常播放？

**Comment by goodnighteveryone** [comment]
> > > 应该是加载缓存的问题吧？视频是需要时间缓存的，那时候会被暂停
> > 
> > 
> > 应该不是吧，做过几次测试，即使在加载几分钟的情况下视频还是会卡在那。最好的情况是有一台电脑的视频能动了，不过因为另一台电脑卡死的缘故，播放几秒之后还会回到和另一台电脑相同的位置再次播放
> 
> 是不是edge卡死？chrome正常播放？

大多数情况是chrome卡死（捂脸），edge有的时候可以在几秒内循环

**Comment by LouisYLWang** [comment]
请问试过其他服务器吗？

**Comment by goodnighteveryone** [comment]
> 请问试过其他服务器吗？

是服务器的问题吗？前一个版本的时候试过其他服务器，综合使用下来这个服务器的体验最好，所以才选择的这个服务器，更新了之后还没有尝试过其他服务器，之后我会测试一下

**Comment by onns** [comment]
我测试了一下，edge确实会有问题，但是你的chrome也会有嘛😂

**Comment by goodnighteveryone** [comment]
> 我测试了一下，edge确实会有问题，但是你的chrome也会有嘛😂

有😂

**Comment by onns** [comment]
问题修复了，确实是我们的问题，最近会发布新版本，不过开发版已经更新了

**Comment by onns** [comment]
可以尝试用一下[开发版](https://github.com/LouisYLWang/Sync-Sofa/archive/multiuser.zip)，会有很多新特性，安装教程:[安装未打包的插件](https://onns.xyz/sync-sofa/#%E5%AE%89%E8%A3%85%E6%9C%AA%E6%89%93%E5%8C%85%E7%9A%84%E6%8F%92%E4%BB%B6)。感谢你的反馈

**Comment by goodnighteveryone** [comment]
> 可以尝试用一下[开发版](https://github.com/LouisYLWang/Sync-Sofa/archive/multiuser.zip)，会有很多新特性，安装教程:[安装未打包的插件](https://onns.xyz/sync-sofa/#%E5%AE%89%E8%A3%85%E6%9C%AA%E6%89%93%E5%8C%85%E7%9A%84%E6%8F%92%E4%BB%B6)。感谢你的反馈

好的，辛苦啦

**Comment by goodnighteveryone** [comment]
> 可以尝试用一下[开发版](https://github.com/LouisYLWang/Sync-Sofa/archive/multiuser.zip)，会有很多新特性，安装教程:[安装未打包的插件](https://onns.xyz/sync-sofa/#%E5%AE%89%E8%A3%85%E6%9C%AA%E6%89%93%E5%8C%85%E7%9A%84%E6%8F%92%E4%BB%B6)。感谢你的反馈

看了支持的站点列表，请问已经支持那种在播放页面里插入了视频页面的网站了吗？

**Comment by onns** [comment]
不行，这种建议网盘代替

**Comment by onns** [comment]
我现在就在看《毒枭》
![Screen Shot 2021-03-13 at 5 39 25 PM (2)](https://user-images.githubusercontent.com/16622934/111026040-1ec6d100-8423-11eb-9493-aba8cf06451f.png)

**Comment by goodnighteveryone** [comment]
> 不行，这种建议网盘代替

我看到已经支持[https://www.dandanzan.com/](https://www.dandanzan.com/)这个站点才想到会不会支持那种网站，请问这个网站和其他站点的区别在哪呢？或者说可以支持其他的界面类似这个站点的网站吗

**Comment by onns** [comment]
`ctrl shift i`打开控制台，按`ctrl f`，搜索`iframe`，视频在这个标签里面就不行，搜索`<video`，有的基本都可以。
![Screen Shot 2021-03-13 at 7 53 38 PM (2)](https://user-images.githubusercontent.com/16622934/111029113-d49b1b00-8435-11eb-8cc4-9c1789dc0463.png)

`iframe`是页面里嵌了子页面，不好操作。

**Comment by goodnighteveryone** [comment]
> `ctrl shift i`打开控制台，按`ctrl f`，搜索`iframe`，视频在这个标签里面就不行，搜索`<video`，有的基本都可以。
> ![Screen Shot 2021-03-13 at 7 53 38 PM (2)](https://user-images.githubusercontent.com/16622934/111029113-d49b1b00-8435-11eb-8cc4-9c1789dc0463.png)
> 
> `iframe`是页面里嵌了子页面，不好操作。

好的，谢谢

**Comment by goodnighteveryone** [comment]
两个人都用的是解压缩版，但是会有两秒的误差，请问这个原因可以修复吗😂

**Comment by onns** [comment]
https://github.com/LouisYLWang/Sync-Sofa/issues/48

**Comment by goodnighteveryone** [comment]
好的，我们再测试一下，谢谢
