### ISSUE TITLE
[BUG] VLC 有时会突然不停跳转至一个时间

### ISSUE THREAD

**Issue by petronny** [LouisYLWang/Sync-Sofa#52]
**感谢你的反馈，在反馈前，请先检查[指南文档常见问题部分](https://github.com/LouisYLWang/Sync-Sofa/blob/dev/readme.md)，若仍无法解决您的问题，请按照格式提供下列信息**

**哪个环节操作发生问题**
播放同步

**请在此处简洁地描述你遇到的问题**

使用的是VLC，在播放时经常会遇到下述问题：

一开始一切正常，有时会突然不停跳转至一个时间。
每隔几秒，就在跳转回发作时的那个时刻。
服务器端观察，首先是每隔几秒就会有一次client operate信息（然而双方其实都没有操作）
然后每次出现client operate就会跳转回那个时刻。

服务器端的log如下：
```
2021/03/17 23:45:49 client tszv0 operate
2021/03/17 23:45:49 client tszv1 operate
2021/03/17 23:45:59 client tszv0 operate
2021/03/17 23:45:59 client tszv1 operate
2021/03/17 23:46:15 client tszv0 operate
2021/03/17 23:46:17 client tszv1 operate
2021/03/17 23:46:23 client tszv1 operate
2021/03/17 23:46:23 client tszv0 operate
2021/03/17 23:46:25 client tszv1 operate
2021/03/17 23:46:31 client tszv1 operate
2021/03/17 23:46:31 client tszv0 operate
2021/03/17 23:46:33 client tszv1 operate
2021/03/17 23:46:39 client tszv1 operate
2021/03/17 23:46:39 client tszv0 operate
2021/03/17 23:46:41 client tszv1 operate
2021/03/17 23:46:47 client tszv1 operate
```

**使用环境**
 - 插件版本号： 最新
 - 连接的服务器域名（如为自建服务器，请注明）：自建，从release page下载的最新binary
 - 操作系统：windows
 - 浏览器型号：chrome
 - 浏览器版本号：88.0.4324.182
 - 下载渠道（插件商店，商店镜像站（请注明），github）：chrome商店

**其他**
如需要，请补充你的问题详情

**截图（可选）**
如方便，请附上问题截图

**Comment by LouisYLWang** [comment]
请参考https://github.com/LouisYLWang/Sync-Sofa/issues/49#issuecomment-797267543 ，
如仍存在跳转至一个时间，请再与我们联系
另：
> 服务器端观察，首先是每隔几秒就会有一次client operate信息（然而双方其实都没有操作）
这个情况是正常的，没有操作时前端也会发包确认状态

**Comment by petronny** [comment]
换了那个comment里的server之后试了一次，问题仍然存在。

不过这次只有一个人在不停复读，另一个人没事。

**Comment by onns** [comment]
用我们提供的服务器也会有这样的问题吗？服务端的日志没有详细的信息，很难定位问题，请参考[如何获取调试信息](https://onns.xyz/sync-sofa/#%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96%E8%B0%83%E8%AF%95%E4%BF%A1%E6%81%AF)，把复读那个人的控制台信息截图上来

**Comment by petronny** [comment]
> 用我们提供的服务器也会有这样的问题吗？

测试过 sync-cn.onns.xyz 和 api.huoranxuanyuan.cn 都有类似问题。

**Comment by onns** [comment]
可以查看一下控制台信息，那个信息比较好定位问题，等你有空可以截图一下

**Comment by petronny** [comment]
今天在bilibili也遇到复读问题了，服务器是 sync-cn.onns.xyz
另一方也是一直正常

console截图如下
![微信截图_20210324212811](https://user-images.githubusercontent.com/5357170/112324083-5a984b00-8ced-11eb-87ef-0103facd1a4f.png)

**Comment by onns** [comment]
看起来像这一方想要和另一边同步时间，可是为什么会一直修改时间失败呢。

**Comment by onns** [comment]
你有办法稳定复现这个鬼畜的情况吗？因为最近很少有人反馈鬼畜情况了 = =，所以一时间很难找到问题，想和你一起测试一下= =

**Comment by petronny** [comment]
没找到稳定办法复现。。。

不过以前不这样，我目前在用1.0.6版本的client和server，我记得可能之后的几个版本应该也没问题。

能帮忙把1.0.7到1.0.10的tag都打一下么，我打算先定位一下是哪个版本出的问题。

还有一个小问题，1.0.6的tag对应的client版本写的还是1.0.5，感觉怪怪的

**Comment by onns** [comment]
每个版本都有一个单独的commit分割的，比如[v1.0.8!!!](https://github.com/LouisYLWang/Sync-Sofa/commit/1d1e8d342237d26bf5cb3455101e718857f569d8)

**Comment by onns** [comment]
你可以下载这个commit的上一次提交，那就是上一个版本。

**Comment by petronny** [comment]
呃，我都回滚到1.0.6了还是会复读。

目前发现的是必定会出现 BLOCKED BECAUSE OF THE LOCK
然后复读

**Comment by onns** [comment]
> 呃，我都回滚到1.0.6了还是会复读。
> 
> 目前发现的是必定会出现 BLOCKED BECAUSE OF THE LOCK
> 然后复读

复读情况我之前自己一直没遇到过，很尴尬

**Comment by onns** [comment]
> 呃，我都回滚到1.0.6了还是会复读。
> 
> 目前发现的是必定会出现 BLOCKED BECAUSE OF THE LOCK
> 然后复读

```js
if (this.socketLock && type == this.SYNCMESSAGE) {
    Debugger.log(`BLOCKED BECAUSE OF THE LOCK`);
    return;
}
```
在1242行，这里的逻辑原因是，在通过代码拖动进度条的时候，也会触发`video`的`listen`事件，然后会把当前的状态发给另一个人，所以会导致两个人一直接收对方的进度，然后一直鬼畜。所以这句话是必定出现的（在非VLC的环境下），VLC条件下应该也是类似的情况。

**Comment by onns** [comment]
想了半小时没发现问题。。。
![112324083-5a984b00-8ced-11eb-87ef-0103facd1a4f](https://user-images.githubusercontent.com/16622934/114580751-b7b26b80-9cb1-11eb-9b87-c9b0b777951f.png)
你能不能补充一下细节，这两个之间发生了什么吗

**Comment by onns** [comment]
代码本身是没有任何对视频的延迟操作的，都是立即执行的。

如果没有接收到变化信息，代码后台只有一个心跳循环在发送当前状态的信息，所以我很好奇这两个变化之间是什么让视频的进度条变了。。。

**Comment by onns** [comment]
VLC的问题我觉得可以试着把刷新频率提高一下看看问题会不会消失，将`handleVLC`函数的`this.VLCTimer = setInterval(function () {}, 1000);`后面的数字改成`100`试试。因为VLC的状态是1秒更新一次的，可能是这个地方的原因。

但既然哔哩哔哩也会出现。。。应该不是这里的问题。

**Comment by petronny** [comment]
> 你能不能补充一下细节，这两个之间发生了什么吗

什么都没发生，中间那个变成0.962643就是复读回去了，然后播放了6秒，然后就又复读回去了。

**Comment by onns** [comment]
> > 你能不能补充一下细节，这两个之间发生了什么吗
> 
> 什么都没发生，中间那个变成0.962643就是复读回去了，然后播放了6秒，然后就又复读回去了。

那你这样一说，问题是出在另一台机器上了，为什么另一台机器6秒之后的时间戳还是1.259没变过？`isPlay=true`说明是在播放状态啊，为什么对方的机器的时间戳一直是1

**Comment by petronny** [comment]
对，对方一直是正常播放的状态

**Comment by onns** [comment]
问题是出在正常播放的那一方。。。下次你再遇见这种情况，打开正常的那一方，看一下那一方的视频时间戳有没有变化，打开控制台然后console直接输入：
```js
var video =  document.querySelector('video');
video.currentTime
```
然后看看这个`video.currentTime`会不会变。

**Comment by onns** [comment]
话说你是不是在切p的时候出现的问题。。。？或者切了视频之类的= =？

**Comment by petronny** [comment]
目前的确切了视频比较容易出现

**Comment by onns** [comment]
> 目前的确切了视频比较容易出现

切p之后要重新连接一下。。。切P的还没实现呢。。。

**Comment by petronny** [comment]
啊这，为啥会不工作了呢。

对VLC来说就是调整个进度条吧

**Comment by petronny** [comment]
但是换了视频以后重连了还是会复读。

就是换了视频，发现复读了，立刻断掉重连，一会儿又复读了。

**Comment by petronny** [comment]
> 下次你再遇见这种情况，打开正常的那一方，看一下那一方的视频时间戳有没有变化

刚才看了一下另一方的log，的确另一方一直都在发送同一个时间

> 然后看看这个video.currentTime会不会变。

这个这次还没试

**Comment by onns** [comment]
> 啊这，为啥会不工作了呢。
> 
> 对VLC来说就是调整个进度条吧

VLC确实没关系，但哔哩哔哩有关系

**Comment by onns** [comment]
> 但是换了视频以后重连了还是会复读。
> 
> 就是换了视频，发现复读了，立刻断掉重连，一会儿又复读了。

你在用哪个版本的代码，最新版本的才支持断掉重连

**Comment by petronny** [comment]
这样，目前还是1.0.6了。

我先切换到最新吧，然后下次复读的时候看看。

**Comment by onns** [comment]
那你按照我[这个](https://github.com/LouisYLWang/Sync-Sofa/issues/52#issuecomment-818841444)改一下最新的`dev`版本的代码，试试VLC吧

**Comment by petronny** [comment]
好，目前是 41f26b30e7caff9f138044e9906081a84db38704 加上那个修改。

下次试试

**Comment by petronny** [comment]
目前发现了一个问题，在这个版本下，调整进度条不同步。

比如A调整到0:00, 对方同步到了 0:08

B调整到了 13:14，A同步到了13:06

**Comment by onns** [comment]
> 目前发现了一个问题，在这个版本下，调整进度条不同步。
> 
> 比如A调整到0:00, 对方同步到了 0:08
> 
> B调整到了 13:14，A同步到了13:06

这个是你俩系统时间的问题，有一个人的系统时间差了8秒

**Comment by petronny** [comment]
啊这样。。。

**Comment by petronny** [comment]
目前出现了几次复读的情况，然而基本上是复读了几遍之后就被纠正了。

**Comment by petronny** [comment]
还有 VLC 页面下
```
var video =  document.querySelector('video');
```
这个返回undefined

**Comment by onns** [comment]
> 还有 VLC 页面下
> 
> ```
> var video =  document.querySelector('video');
> ```
> 
> 这个返回undefined

VLC没有这个属性。。。。之前问题不是已经找到了吗

**Comment by onns** [comment]
> 目前出现了几次复读的情况，然而基本上是复读了几遍之后就被纠正了。

你是改小了时间吗

**Comment by petronny** [comment]
> 你是改小了时间吗

就是把那个timer从1000改成了100

复读过程中双方什么都没做，就一直播放

**Comment by onns** [comment]
> 目前出现了几次复读的情况，然而基本上是复读了几遍之后就被纠正了。

如果有复读的那个时间段的日志，就比较好分析了。。。

**Comment by petronny** [comment]
日志上看的确是还是发送的重复的时间，原因未知。

要不多在console里 log 几个点？

**Comment by onns** [comment]
> 日志上看的确是还是发送的重复的时间，原因未知。
> 
> 要不多在console里 log 几个点？

你截图我康康，我说不定能看出来

**Comment by petronny** [comment]
好，下次

**Comment by petronny** [comment]
![微信截图_20210415215021](https://user-images.githubusercontent.com/5357170/114880410-9e85f800-9e34-11eb-8684-e66250a0a090.png)

这个是从开头到出现若干次复读的截图

**Comment by petronny** [comment]
经过多次尝试，发现出现该问题的主要原因是有一方把VLC的网页最小化了。。。

都开着的话貌似就不太容易复读了

**Comment by petronny** [comment]
保持VLC的标签页在最上面，且浏览器没有最小化的话，目前就很少出现这个问题了。
