### ISSUE TITLE
[BUG]点击start之后没反应，是否是服务器掉线了？另外bilibili无法同步观看番剧或电影了

### ISSUE THREAD

**Issue by MaboroneSeika** [LouisYLWang/Sync-Sofa#59]
**感谢你的反馈，在反馈前，请先检查[指南文档常见问题部分](https://github.com/LouisYLWang/Sync-Sofa/blob/dev/readme.md)，若仍无法解决您的问题，请按照格式提供下列信息**

**哪个环节操作发生问题**
（插件安装/插件界面/申请连接码/连接用户/播放同步/设置选项/其他：请注明）

申请连接码及播放同步

**请在此处简洁地描述你遇到的问题**

点击start之后没反应，并且之前连接正常的情况下在bilibili观看番剧或电影时，无法同步

**使用环境**
 - 插件版本号： 1.0.11
 - 连接的服务器域名（如为自建服务器，请注明）：sync-cn.onns.xyz
 - 操作系统：windows11
 - 浏览器型号：microsoft edge
 - 浏览器版本号：113.0.1774.57 (正式版本) (64 位)
 - 下载渠道（插件商店，商店镜像站（请注明），github）：github

**其他**
如需要，请补充你的问题详情

**截图（可选）**
如方便，请附上问题截图

**Comment by LouisYLWang** [comment]
@MaboroneSeika 感谢反馈，国内服务器应该已经修复Thanks @onns
