### ISSUE TITLE
Netflix support

### ISSUE THREAD

**Issue by AkazaRenn** [LouisYLWang/Sync-Sofa#6]
Love this extension, please add Netflix support, thank you!

**Comment by LouisYLWang** [comment]
I tried but failed, it seems Netflix blocks DOM manipulation from extenstion scripyt, but I will find other way around, thanks for your suggestion.

**Comment by LouisYLWang** [comment]
hi, due to the policy of netflix, we still can not support netflix, check this https://help.netflix.com/en/node/66763?accordionCategory=windows_computer
