### ISSUE TITLE
点击图标后的激活太久了

### ISSUE THREAD

**Issue by happyTonakai** [LouisYLWang/Sync-Sofa#8]
Edge Chromium 版本 80.0.361.111 (官方内部版本) (64 位)
Win 10 64bit

测试网站 bilibili，点击图标之后需要很长时间才能打开插件的页面，可能长达半分钟到一分钟，甚至点开其他视频了才弹出来。

（顺便问一下目前支持倍速播放吗？还有切换视频（分p或者干脆点开其他视频了）还会继续同步吗？）

**Comment by LouisYLWang** [comment]
暂时还没有用edge测试过，但是在Chrome 81.0.4044.92测试没发现插件弹窗滞后问题。这个情况是存在于所有网页吗？ 

切换分P的话目前可以手动切换，只要两个人都切换了分p，理论上不需要重新建房间，刚刚测试是没有问题的。

倍速播放可以尝试下个版本支持一下， 感谢反馈

**Comment by happyTonakai** [comment]
我用 Chrome 测试了一下，版本 81.0.4044.92，关闭所有其他插件，关闭http代理，b站和YouTube都存在这个问题。具体问题出在哪我也不知道，能否提供日志功能方便反馈？

是否可以理解为插件不需要在特定视频网站中激活，打开浏览器激活进入房间后再打开视频网页，双方只要url相同就没问题？哪怕先上b站再上油管都可以继续同步？

**Comment by LouisYLWang** [comment]
跨网站是不行的，只要页面没有刷新，注入的脚本就会继续保持socket连接，理论上就可以继续连接，所以分p是支持的。

日志目前还没有，麻烦在chrome://extensions/?id=kgpnhgmpijhpkefpddoehhminpfiddmg打开collect errors 然后查看一下是否有报错信息

**Comment by happyTonakai** [comment]
明白了。

没有报错信息，我想大概是网络的问题。

刚刚我开启了全局代理模式，在 Edge 中试了一下可以迅速地激活，再关闭代理依然可以；
保持代理关闭的状态去 Chrome 里试还是非常慢，再开全局 Chrome 也可以快速打开了，关闭代理后依然保持这个状态。

**Comment by LouisYLWang** [comment]
奇怪。。我的脚本里应该没有需要CDN加载的内容，在request code之前也不需要连接服务器，我再查查看

**Comment by onns** [comment]
现在可以看看是否会出现类似问题了，如果还存在，建议换一个服务器，最近有添加服务器支持，详细可以移步[文档](https://onns.xyz/sync-sofa/)
